import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import CustomNavBar from "@/components/CustomNavBar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import UserContext from "@/context/userContext";

const inter = Inter({ subsets: ["latin"] });

// as for each page we are creating their own title
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // this children is here will show the page.js component
  // page.js is like index.js
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <h1> Header </h1> */}
        {/* we can use the client side component here within the server side  */}
        <UserContext>
          <ToastContainer />
          <CustomNavBar />
          <div>
            <div className="mt-0">{children}</div>
          </div>
          <Footer />
        </UserContext>
      </body>
    </html>
  );
}
